version: "3"
services:
  web:
    build: .
    ports:
      - "5000:8000"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      QUEUE_NAME: test
    links:
      - "redis"
  redis:
    image: "redis:alpine"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
