apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: simpleingressroute
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`app.192.168.1.52.nip.io`)
      kind: Rule
      services:
        - name: app-production-service
          port: 8000
