apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prometheus-ingressroute
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`prometheus.192.168.1.52.nip.io`)
      kind: Rule
      services:
        - name: prometheus-k8s
          port: 9090
