---
apiVersion: v1
kind: Secret
metadata:
  name: basic-auth-secret
  namespace: default
data:
  auth: dXNlcjokMnkkMDUkNnpvSU1NYVd2SG1FVldJR2ZHUVhBZXFrVVJXaTI0cXRHVmdzdUcxNmdta1U1UFFXRm5iZTYK
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: basic-auth
  namespace: default
spec:
  basicAuth:
    secret: basic-auth-secret
