apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: traefik-monitor
  labels:
    app: traefik
spec:
  selector:
    matchLabels:
      app: traefik
  namespaceSelector:
    any: true
  endpoints:
    - port: web
      path: /traefik/metrics
