apiVersion: v1
kind: Service
metadata:
  name: traefik-service
  labels:
    app: traefik
spec:
  type: LoadBalancer
  ports:
    - name: web
      protocol: TCP
      port: 80
    - name: websecure
      protocol: TCP
      port: 443
  selector:
    app: traefik
