apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-ingressroute
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`grafana.192.168.1.52.nip.io`)
      kind: Rule
      services:
        - name: grafana
          port: 3000
